---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by David.
--- DateTime: 16-07-2024 22:31
---
function hogwartsRefresh(cardZone, drawZone, refillParameter)
    if cardZone.getObjects()[1] == nil then
        for i, v in pairs(drawZone.getObjects()) do
            if v.tag == 'Deck' then
                drawZone.getObjects()[i].takeObject(refillParameter)
            elseif v.tag == 'Card' then
                drawZone.getObjects()[i].flip()
                drawZone.getObjects()[i].setPositionSmooth({cardZone.getPosition().x, cardZone.getPosition().y, cardZone.getPosition().z})
            end
        end
    end
end

--For finding code for cleaning up unused players: buttonClickedDestroyHarry()

-- Position for choices must be below this: position = {16.50, 1.05, 9.00}